version: '3.1'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    container_name: foodgram-backend
    image: rt4otohub/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: .env
    container_name: foodgram-front
    image: rt4otohub/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    container_name: foodgram-nginx
    image: rt4otohub/foodgram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/static 
      - media:/media