# Generated by Django 3.2.3 on 2024-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredients_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
