# Generated by Django 3.2.3 on 2024-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240913_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название рецепта'),
        ),
    ]
