# Generated by Django 3.2.3 on 2024-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240915_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=255, verbose_name='Оригинальная ссылка')),
                ('short_url', models.CharField(max_length=132, unique=True, verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'короткие ссылки',
            },
        ),
    ]
