# Generated by Django 3.2.3 on 2024-09-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
        migrations.RenameField(
            model_name='shortlink',
            old_name='long_url',
            new_name='origin_url',
        ),
    ]
